version: "3.7"

services:
  big_blue_buttton:
    image: bigbluebutton/bigbluebutton
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80
    ports:
      - "8888:80/tcp"
      - "1935:1935"
      - "3478:3478"
      - "3478:3478/udp"
    command: "-h localhost"
