bbb:
  api:
    type: config_object
    label: API configs
    mapping:
      version:
        type: string
        label: Verion of the BBB API
  settings:
    type: config_object
    label: Module settings configs
    mapping:
      security_salt:
        type: string
        label: Salt string for API cals
      base_url:
        type: string
        label: Base url of BBB server
