bbb:
  api:
    type: config_object
    label: API configs
    mapping:
      version:
        type: string
        label: Verion of the BBB API
  settings:
    type: config_object
    label: Module settings configs
    mapping:
      security_salt:
        type: string
        label: Salt string for API cals
      base_url:
        type: string
        label: Base url of BBB server
      display_mode:
        type: string
        label: Display mode
      display_height:
        type: string
        label: Display height
      display_width:
        type: string
        label: Display width
      local_tasks:
        type: string
        label: Local task
  bbb_node_type.*:
      type: config_entity
      label: 'Content type'
      mapping:
        id:
          type: string
          label: 'Machine-readable name'
        uuid:
          type: string
          label: 'Machine-readable name'
        label:
          type: label
          label: 'Name'
        active:
          type: string
          label: 'Machine-readable name'
        showLinks:
          type: string
          label: 'Machine-readable name'
        showStatus:
          type: string
          label: 'Machine-readable name'
        moderatorRequired:
          type: string
          label: 'Machine-readable name'
        welcome:
          type: string
          label: 'Machine-readable name'
        dialNumber:
          type: string
          label: 'Machine-readable name'
        moderatorPW:
          type: string
          label: 'Machine-readable name'
        attendeePW:
          type: string
          label: 'Machine-readable name'
        logoutURL:
          type: string
          label: 'Machine-readable name'
        record:
          type: string
          label: 'Machine-readable name'
#          type:
#            type: string
#            label: 'Machine-readable name'
#          description:
#            type: text
#            label: 'Description'
#          help:
#            type: text
#            label: 'Explanation or submission guidelines'
#          new_revision:
#            type: boolean
#            label: 'Whether a new revision should be created by default'
#          preview_mode:
#            type: integer
#            label: 'Preview before submitting'
#          display_submitted:
#            type: boolean
#            label: 'Display setting for author and date Submitted by post information'
#node.type.*.third_party.bbb:
#  type: config_entity
#    label: 'Content type'
#    mapping:
#      id:
#        type: string
#        label: 'Machine-readable name'
#      uuid:
#        type: string
#        label: 'Machine-readable name'
#      label:
#        type: label
#        label: 'Name'
#      active:
#        type: string
#        label: 'Machine-readable name'
#      showLinks:
#        type: string
#        label: 'Machine-readable name'
#      showStatus:
#        type: string
#        label: 'Machine-readable name'
#      moderatorRequired:
#        type: string
#        label: 'Machine-readable name'
#      welcome:
#        type: string
#        label: 'Machine-readable name'
#      dialNumber:
#        type: string
#        label: 'Machine-readable name'
#      moderatorPW:
#        type: string
#        label: 'Machine-readable name'
#      attendeePW:
#        type: string
#        label: 'Machine-readable name'
#      logoutURL:
#        type: string
#        label: 'Machine-readable name'
#      record:
#        type: string
#        label: 'Machine-readable name'
